### ISSUE TITLE
Remove Forms plugin from v3 docs?

### ISSUE THREAD

**Issue by kenmorse** [tailwindlabs/tailwindcss.com#1068]
It seems Tailwind CSS v3 includes great form support out-of-the-box and no longer needs the Forms plugin. If that's the case, should the plugin be removed from the list of plugins in the v3 docs?

**Comment by Triloworld** [comment]
Same as?: https://github.com/tailwindlabs/tailwindcss-aspect-ratio/issues/31
It can support more browsers and more options as it is plugin. 
Forms plugins support "class" strategy so it isn't same as in core one.

Reference:
https://tailwindcss.com/docs/plugins#forms
https://tailwindcss.com/docs/hover-focus-and-other-states#form-states

**Comment by reinink** [comment]
Hey! So while we've added some new features in Tailwind CSS v3.0 for styling form inputs (like the [accent color](https://tailwindcss.com/docs/accent-color) utilities and [file input button](https://tailwindcss.com/docs/hover-focus-and-other-states#file-input-buttons) modifier), the form plugin is still very useful, as it provides a helpful reset for form styles, making it possible to style form inputs with Tailwind's utilities.

The aspect ratio plugin is also useful still, since not all browsers support the native `aspect-ratio` property yet. You can read more about that [here](https://github.com/tailwindlabs/tailwindcss-aspect-ratio#compatibility-with-default-aspect-ratio-utilities).

**Comment by kenmorse** [comment]
Thanks very much for those clarifications, @reinink.
