### ISSUE TITLE
Suggestion: add note about "legacy mode" for Typography plugin

### ISSUE THREAD

**Issue by MichaelAllenWarner** [tailwindlabs/tailwindcss.com#1078]
The new version of Typography uses `:where()` selectors to allow for `.no-prose` embeds and to lower the specificity of the Typography rules. It also comes with a `target` option that, [when set to `"legacy"`](https://github.com/tailwindlabs/tailwindcss-typography/blob/61826feebf24cc1c09630fef4aa699afd58e5dac/src/index.js#L48), disables the `:where()` selectors.

The `target` option is vital information for Typography users who need to support any versions of [Safari < 14](https://caniuse.com/mdn-css_selectors_where), which is surely a lot of us, alas. This warrants mention in [the docs](https://tailwindcss.com/docs/typography-plugin).

**Comment by reinink** [comment]
@MichaelAllenWarner Hey thanks for this feedback! Originally we weren't even planning on adding the `legacy` option, since it's unlikely to affect that many users as these browsers continue to decline in use. However, we decided to add it on the off chance someone bumps into this and reaches out for help, but we're okay leaving at that — I don't think it's necessary to officially document. Hope that makes sense, and I appreciate the input either way! 👍

**Comment by MichaelAllenWarner** [comment]
@reinink 

That makes sense.

I still recommend mentioning in the docs that the plugin won't work in Safari 13 and below (because of `:where()`). I know Safari 15 is out now, but I work at an agency with big clients, and I definitely still get complaints if things are broken in Safari 13, so I foresee this being a problem for unsuspecting devs for a while yet. Just my 2¢!

**Comment by reinink** [comment]
@MichaelAllenWarner I appreciate you taking the time to share that. I think we're going to leave it as it is, but if we start getting more folks asking about this, we'll definitely revisit it 👍
