### ISSUE TITLE
The way to import Tailwind directly has been removed from Next.js installation guide

### ISSUE THREAD

**Issue by dqn** [tailwindlabs/tailwindcss.com#1083]
In v2, 2 ways to include Tailwind were introduced. However, in v3, the direct import way has been removed.

v2: https://v2.tailwindcss.com/docs/guides/nextjs#include-tailwind-in-your-css
v3: https://tailwindcss.com/docs/guides/nextjs

That way still seems to work, but has it been deprecated?

**Comment by adamwathan** [comment]
Hey! Yep still works, not deprecated, just didn’t want to make the documentation confusing by documenting multiple ways to do the same thing. Decided to document the option we did because it’s the only way for people to add custom CSS if needed. Think of the other option as an advanced shortcut for people who know they won’t ever be writing any custom CSS.
