### ISSUE TITLE
docs is missing `bg-opacity-*` `text-opacity-*` ...

### ISSUE THREAD

**Issue by bourhaouta** [tailwindlabs/tailwindcss.com#1182]
I can't find `bg-opacity-*`, `text-opacity-*` ... in the docs, and the migration page doesn't say anything about removing them

Are we going to be able to use them in future releases?

**Comment by adamwathan** [comment]
Hey! We consider them deprecated but have no plans to remove them any time soon if ever, which is why we left it out of the migration guide since it's not necessary to make any changes to your code. Just not documenting them going forward and encouraging people to use the opacity modifier instead (like `bg-gray-500/20`).
