### ISSUE TITLE
The search modal has few UX issues.

### ISSUE THREAD

**Issue by pratyushtewari** [tailwindlabs/tailwindcss.com#1188]
1. It opens up into a modal from a text input.
2. it the search text input is a button, then it is designed like a text input.
3. Basically, please either change the search bar to look like a button or make it an actual text input.

How about this?

<img width="1120" alt="Frame 4" src="https://user-images.githubusercontent.com/251768/153055602-bb1b40c9-8576-4741-8654-f36dbe6f8680.png">

P.S. I am a designer to I can mostly contribute with design ideas.

**Comment by adamwathan** [comment]
Thanks for the feedback ❤️ but we are happy with how it is.

**Comment by pratyushtewari** [comment]
I wish you could see the UX issue beyond your personal likeness so that the UI is more clear and efficient for everyone. But thanks for checking reply anyways.

**Comment by adamwathan** [comment]
Everyone knows to click it, it's not less efficient. It's the same number of steps. Here's another example from a company with very talented designers who made the same decision:

https://stripe.com/docs/api

If anything, styling it like an input is more efficient because people expect search to be an input field. If we styled it like a button I expect it would be harder for people to find. The reason that it is implemented as a modal dialog is because we rely on Algolia's DocSearch product, and that's how that product is designed and built, and I assume they have good reasons for it too as they are a talented team.

Again I appreciate your feedback but without empirical evidence for why this is an actual problem, it is simply your own personal preference which is no more valid than my own. I don't appreciate the implication that we don't know what we're doing.
