### ISSUE TITLE
About archiving of postcss-nesting

### ISSUE THREAD

**Issue by yogarasu** [tailwindlabs/tailwindcss.com#1274]
postcss-nesting is integrated and archived in postcss-preset-env.
https://github.com/csstools/postcss-plugins/discussions/75

The current documentation seems to recommend postcss-nesting
I think it needs to be fixed so that I don't accidentally use postcss-nesting like I do.
https://tailwindcss.com/docs/using-with-preprocessors#nesting

Since the following warning is displayed in post.config.js, I wrote `tailwindcss/nesting': {}` to avoid it, but I could not confirm whether this was correct, so I issued an issue here for the time being.

> (11:3) Nested CSS was detected, but CSS nesting has not been configured correctly.
> Please enable a CSS nesting plugin *before* Tailwind in your configuration.
> See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting

```js
module.exports = {
  plugins: {
    'tailwindcss/nesting': {},  // 
    tailwindcss: {},
    'postcss-preset-env': {
      stage: 3,
      features: {
        'nesting-rules': true,
      },
    },
    autoprefixer: {},
  },
}
```

**Comment by thecrypticace** [comment]
Hey! You're correct in pointing out that `postcss-nesting` was indeed moved to a different organization / repo. However, it is still available to use individually: https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting#usage

Our nesting plugins lets you choose one of two plugins to use: `postcss-nested` (the default) or `postcss-nesting`. We don't explicitly recommend one plugin over the other but we do provide instructions on how to use either one. You can enable the use of `postcss-nesting` by specifying the plugin in your postcss config like so:

```js
module.exports = {
  plugins: {
    'tailwindcss/nesting': 'postcss-nesting',  // I changed this line from your example
    tailwindcss: {},
    'postcss-preset-env': {
      stage: 3,
      features: {
        'nesting-rules': true,
      },
    },
    autoprefixer: {},
  },
}
```

Since you are using `postcss-present-env` you do probably want to use `'tailwindcss/nesting': 'postcss-nesting',` in your config. Hope that helps!

**Comment by yogarasu** [comment]
@thecrypticace 

I may have just misunderstood.
I thought the value of'tailwindcss / nesting', `postcss-nesting`, would indicate the plugin to use, but maybe it just indicates the mode to use another plugin?

**Comment by thecrypticace** [comment]
Ah so **our** plugin is called `tailwindcss/nesting` and it wraps other CSS plugins so we can use them before Tailwind CSS runs. Using our nesting plugin does not necessarily mean that `postcss-nesting` is being used unless you've configured it to do so. Here are the following configurations that you can technically use to specify which plugin to use:

```js
'tailwindcss/nesting': {},                // Have Tailwind use the default plugin (currently postcss-nested)
'tailwindcss/nesting': 'postcss-nested',  // Explicitly have Tailwind use postcss-nested
'tailwindcss/nesting': 'postcss-nesting', // Explicitly have Tailwind use postcss-nesting
```

So yeah it just indicates which plugin that Tailwind uses to process the incoming CSS to flatten nested CSS.
