### ISSUE TITLE
Accent color HoverFocusAndOtherStates is confusing

### ISSUE THREAD

**Issue by carlmjohnson** [tailwindlabs/tailwindcss.com#1376]
Accent color starts by saying you can set the hover color with hover:, then it gives an example with focus: and says not to use hover:. It's a confusing reading experience. I think the problem is that `<HoverFocusAndOtherStates>` adds the same boilerplate prefer to accent color as it does to everything else, even though it doesn't really apply.

**Comment by thecrypticace** [comment]
The documentation does not say you _can't_ use hover and active. You definitely can: https://play.tailwindcss.com/GZXmLWszbH

> Note, while it’s possible to set an accent color using the hover and active modifiers, **_the resulting color will be slightly different than what you set_**, as browsers automatically adjust the brightness of the accent color for these two states.

This means that, for both the hover _and_ active states, the result won't be exactly the color you set because the browser adjusts the final color — which we do not have control over.

**Comment by carlmjohnson** [comment]
I just think it's confusing that the boilerplate says "hover" then the example says "focus" then the next paragraph says don't use hover most of the time. It's bouncing back and forth on what it's talking about.
