### ISSUE TITLE
No playground link on the start page

### ISSUE THREAD

**Issue by alvarlagerlof** [tailwindlabs/tailwindcss.com#1379]
I found myself wanting to open the playground, now knowing what it was called. I went to tailwindcss.com and pressed ctrl+f and searched "play" but found no results. Googling did of course work, but it wasn't what I thought about first.

So, what about a link to Tailwind Play somewhere on the start page? If not at the top, maybe in the footer?

**Comment by adamwathan** [comment]
Thanks for the feedback! Figuring out how to surface everything is tough for sure and this is something I've thought about but not been able to come up with a good answer. It doesn't quite fit in the top nav currently when the Tailwind CSS v3.1 banner is visible, so it's a bigger project than it sounds like trying to figure out how to get it all there. Plus the more you add, the less discoverable the existing items are because they have more to compete with.

Will keep thinking on it but going to close the issue as we try to keep issues to actual mistakes/bugs/etc. 👍
