### ISSUE TITLE
"Adding smaller breakpoints" section no longer completely accurate

### ISSUE THREAD

**Issue by kiongomutwe** [tailwindlabs/tailwindcss.com#1425]
This should be added to the docs https://discord.com/channels/486935104384532500/1034003338695544864/1034099681837461674

**Comment by reinink** [comment]
Hey! 👋

I know you're (brand) new to GitHub and just trying to help, but issues need much more detail than this, and can't simply link out to Discord for more information.

That said, having read your discussion on Discord, the "[Adding smaller breakpoints](https://tailwindcss.com/docs/screens#adding-smaller-breakpoints)" section isn't completely accurate any more and should probably eventually be adjusted, since as of Tailwind CSS v3.2, you can use `extend` to add new smaller breakpoints, as long as you're using a simple breakpoint configuration where each breakpoint is defined as a simple string value, and doesn't have any `max-width` breakpoints defined or range-based media queries.

However, since the technique outlined in this section is still required for folks on earlier versions of Tailwind CSS v3.x, I think it's best that we leave this section for now — and it's honestly still a good approach for v3.2. Maybe we remove or adjust it for v4.

Thanks for reporting this either way! 🤙
