### ISSUE TITLE
Sveltekit documentation improvement suggestion

### ISSUE THREAD

**Issue by mikeyhogarth** [tailwindlabs/tailwindcss.com#1458]
Followed the [documentation](https://tailwindcss.com/docs/guides/sveltekit) for usiung Tailwind with Sveltekit - it was all working swimmingly...

```html
<!-- This works fine -->
<button>Hello World</button>

<style>
button {
  @apply text-white;
}
</style>
```
Until I used any of the utility styles such as `hover:`...
```html
<!-- This breaks -->
<button>Hello World</button>

<style>
button {
  @apply text:white hover:bg-green-100;
}
</style>
```
At which point, the linter started failing with the message "Semicolon or block is expected".  A lot of Googling later, and I found a whole bunch of other people have had this issue but nobody had solved it (a few people even recommending "switching off the linter"! - but I eventually figured out what it was. 

You need to specify `lang="postcss"` in the style block attributes. Soon as I did that, it started working as expected.

```html
<!-- This is how you get it working -->
<button>Hello World</button>

<style lang="postcss">
button {
  @apply text:white hover:bg-green-100;
}
</style>
```
I feel like this is worth pointing out somewhere on the [setup page for Sveltekit](https://tailwindcss.com/docs/guides/sveltekit) - I had been working away for some hours before this problem manifested itself (everything works just fine until you start using those utility classes!) and I lost quite a lot of time to the issue before I figured out what I needed to do.

Let me know what you think - I'd be happy to put a PR together if you agree. Could be either:

* An additional comment in step 3 about making sure you remember `lang="postcss"`
* OR Including a `style` block in the example given in step 8 so as to demonstrate.

**Comment by thecrypticace** [comment]
This exact issue is why we have people install Svelte Preprocess — the build fails when using variants with `@apply` in `<style>` blocks otherwise. It's included by default in the skeleton but not in the demo project oddly enough. We'll discuss it internally to see what we can clarify.

**Comment by mikeyhogarth** [comment]
Just to clarify - I followed the setup guide exactly, the step about configuring `preprocess` in the guide is clear already - the part I think needs mentioning in the docs is that you *then* need to make sure you use `<style lang="postcss">` when using the component-adjacent style blocks otherwise the `hover:` etc. utility classes crash the builds - this part isn't mentioned in the docs at all (although admittedly this is all more of a Svelte thing than a Tailwind thing).

**Comment by mikeyhogarth** [comment]
Absolutely - I'll put a repo together that demonstrates the issue - thanks again.

**Comment by mikeyhogarth** [comment]
Example project demonstrating the issue -> https://github.com/mikeyhogarth/sveltekit-tailwind

Although I think the misunderstanding between it being the linter vs the build probably explained the discrepancy.

**Comment by reinink** [comment]
@mikeyhogarth Hey thanks for sharing this suggestion. However to be completely honest we've actually tried to discourage using per-component styles in this way in our documentation.

The reason why is because under-the-hood frameworks like Vue and Svelte process every single `<style>` block independently — running your PostCSS plugin chain against each one in isolation. That means if you have 10 components that each have a `<style>` block, Tailwind is being run 10 separate times for each one.

Not only is this slow, it's also caused a lot of confusion for folks trying to mix-in classes from other components using `@apply`. You can read more about that particular issue here:

https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css

So given that our recommendation is to not use per-component styles when using Tailwind, I think it's best to leave any mention of style blocks out of our Svelte framework guide.

I hope that makes sense!

**Comment by mikeyhogarth** [comment]
Cheers makes sense - I had no idea these were discouraged!

**Comment by mikeyhogarth** [comment]
@reinink sorry to bring this back up - the third step in the [Sveltekit setup guide](https://tailwindcss.com/docs/guides/sveltekit):

> Enable use of PostCSS in <style> blocks
> In your svelte.config.js file, import svelte-preprocess and configure it to process <style> blocks as PostCSS.

If the recommendation is to not use per-component styles when using Tailwind, should this step maybe mention that? Maybe with a link to [the resource you mentioned](https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css) above? Unless I'm missing something, this is an entire step dedicated to setting up the thing that is being discouraged.
