### ISSUE TITLE
Transition between light/dark themes breaks in documentation

### ISSUE THREAD

**Issue by ZoreAnkit** [tailwindlabs/tailwindcss.com#1470]
**What browser are you using?**

Chrome Version 108.0.5359.94

**What operating system are you using?**

Ubuntu 20.04

**Reproduction URL**

[Official website](https://tailwindcss.com/docs/installation)

**Describe your issue**

When I change to dark theme on official website somethings break and UI doesn't look normal. It gets fixed when i refresh page check below video for reference

[screencast-nimbus-capture-2022.12.21-18_10_28.webm](https://user-images.githubusercontent.com/46300882/208907767-fbe64b51-53d1-4730-be2d-e8153d4769a2.webm)

**Comment by bradlc** [comment]
Hey @ZoreAnkit. Do you have any browser extensions installed that could be causing this? Does this still happen if you disable all extensions?

**Comment by ZoreAnkit** [comment]
Hey @bradlc, Yes I disabled all extensions but still bug exists.

https://user-images.githubusercontent.com/46300882/216327886-b0aceaa4-e1f0-4b84-9f1e-469de424861a.mp4

**Comment by bradlc** [comment]
Interesting! When this happens what `background-color` style is applied to the `body` element when you look in DevTools?

In light mode it should be this:

<img width="328" alt="CleanShot 2023-02-02 at 12 49 18@2x" src="https://user-images.githubusercontent.com/2615508/216329380-8250a13e-0fc7-461f-956b-92fd31a37027.png">

And in dark mode it should be this:

<img width="336" alt="CleanShot 2023-02-02 at 12 49 39@2x" src="https://user-images.githubusercontent.com/2615508/216329472-68a32c25-e6f6-4b7b-ab3c-9ee8f0b4b7fe.png">

Is there some other style overriding those or something?

**Comment by ZoreAnkit** [comment]
No I don't see any styles overriding this classes

**Comment by reinink** [comment]
@ZoreAnkit Hey! So despite our best efforts to reproduce this issue using Ubuntu 20.04 (via Parallels) with Chromium installed, we've been unable to do so — everything seems to work fine for us. This makes it really hard for us to determine if there is a real bug here, or if it's something localized to your particular system.

Given that, and the fact that we haven't had any others reporting this issue, I think I am just going to close this one for now.

Hope that makes sense 🙏
