### ISSUE TITLE
snap behavior

### ISSUE THREAD

**Issue by uforek** [tailwindlabs/tailwindcss.com#1525]
Turns out you have to include overflow-scroll to allow snapping to work. Is this something that is obvious? The docs failed to mention this.

**Comment by reinink** [comment]
Hey! So yeah I think in this particular situation it's reasonable to assume that you need a scrollable container in order to enable scroll snapping, but I can totally appreciate that this may not be super obvious if you're new to these properties.

This has always been the struggle when writing our documentation — knowing exactly how much code to show in our snippets. In general we've tried to only show the most relevant classes needed to get the concept across, but that does mean sometimes that there are other necessary classes that aren't shown.

In situations where our code snippet isn't clear enough for you, or you're just struggling to get something to work, my recommendation would be to view the source of our demos to see how we've actually built them.

Good luck! 💪
