### ISSUE TITLE
Nextjs tutorial assumes `create-next-app`

### ISSUE THREAD

**Issue by mmkal** [tailwindlabs/tailwindcss.com#1539]
Hi! I'm trying to add tailwind to an existing nextjs project. [The nextjs guide](https://tailwindcss.com/docs/guides/nextjs) at first says

>Start by creating a new Next.js project if you don’t have one set up already. The most common approach is to use [Create Next App](https://nextjs.org/docs/api-reference/create-next-app).

which implies create-next-app is optional. then later it says

>Add the @tailwind directives for each Tailwind’s layers to your globals.css file.

I don't have a globals.css file. Currently, the project is using `styled-components` - in fact the [styled-components-babel](https://github.com/vercel/next.js/tree/canary/examples/with-styled-components-babel) nextjs example has the same problem if you need a minimal repro. If globals.css is something created by create-next-app - could the docs be amended to tell us where to create one? In the `public/` folder?

**Comment by reinink** [comment]
Hey! So we've intentionally written all our guides from the perspective of a new project, just because it creates a minimal set of reproducible steps that someone can follow to get Tailwind CSS up and running with that particular framework.

It's nearly impossible to write these guides in such a way that it takes into account all the possible different project configurations someone may have, plus it would also make the guides quite long and complicated.

So if you're adding Tailwind CSS to an existing project, you'll need to adapt our instructions for your particular setup, which I totally appreciate may not be as straight-forward, but our hope is that our guides still provide enough of the key pieces necessary to figure it out.

Hope that makes sense!
