### ISSUE TITLE
Home Page: Hiding SearchButton between different display sizes

### ISSUE THREAD

**Issue by vamsikun** [tailwindlabs/tailwindcss.com#1618]
The following `SearchButton` will be visible only when the display is less than the medium size
https://github.com/tailwindlabs/tailwindcss.com/blob/102eb9117ecc16573885ea3f8de6671c4a7686b9/src/pages/index.js#L46

This `SearchButton` will be visible only when the display is greater than the smaller display size
https://github.com/tailwindlabs/tailwindcss.com/blob/102eb9117ecc16573885ea3f8de6671c4a7686b9/src/pages/index.js#L111

Because of this, when the display is between small and medium, we are able to see both `SearchButton` components.

Wanted to know, if this kind of functionality is made deliberately or is it a bug?

**Comment by thecrypticace** [comment]
Hey! This wasn't exactly intentional but we don't see a problem with keeping it the way it is. It's more a factor of the individual elements, how the design came together, and the space we have available at those specific breakpoints.

So, at least for now, we don't seed a need to change it. Thanks anyway for pointing it out! ✨
