### ISSUE TITLE
[Suggestion] How about `copy-and-paste` tailwindcss class?

### ISSUE THREAD

**Issue by ojj1123** [tailwindlabs/tailwindcss.com#1660]
Hello.
I am a tailwindcss user. I often use tailwindcss for rapid product development. Since there are so many classes, I often check the official documentation.
I want to propose a function in the scenario below, so I create an issue.

> [Scenario]
> 1. Select one of the table of contents (eg `Flex`, `Grid`, `Width`, `Height`, etc.)
> 2. When you enter Flex, drag the required class or click and drag the mouse 3 times quickly. (See the video below)
> 
> https://github.com/tailwindlabs/tailwindcss.com/assets/33178048/4688b88d-de68-4513-a44e-4c6e62c9b3bb
> 
> 3. Copy the dragged class (command + c or ctrl + c).
> 4. Paste (command + v or ctrl + v) where needed.

If you look at No.2 of the above scenario, the action of “drag or click the mouse 3 times quickly” is repeated.
How about **adding the ability to copy classes** to the tailwindcss official documentation? I think it would be convenient to be able to copy to the clipboard with a single mouse click.

[radix-ui Icon](https://www.radix-ui.com/icons) also has **a function to copy svg with one mouse click**. Similarly, **I propose a function to copy the desired class to the clipboard with a single mouse click.**

**Comment by adamwathan** [comment]
Thanks for the suggestion! I think it could be useful if implemented nicely and in a way that it wasn't surprising to people who aren't expecting it (since it just looks like text) but not sure when or if we'll get a chance to make designing this experience our top priority. Going to close this in the mean time since we try to use issues strictly for bugs, but again appreciate the idea.
