### ISSUE TITLE
Documentation on stack order does not mention arbitrary selectors or important flag

### ISSUE THREAD

**Issue by spaceemotion** [tailwindlabs/tailwindcss.com#1662]
The [section on modifier stack order](https://tailwindcss.com/docs/hover-focus-and-other-states#ordering-stacked-modifiers) only contains information about regular modifiers, but is missing two things:

1. Arbitrary child selectors (like `[&>*.foo-bar]`)
2. How to deal with the important flag/plugin (by adding `!`).

I have recently came across an issue with the order of operations while having to do both, for the following snippet:
(https://play.tailwindcss.com/ZzWLU3Vs5F)

```html
<div class="m-6 flex -space-x-px [&>:not(:first-child)]:!rounded-l-none [&>:not(:last-child)]:!rounded-r-none">
  <div class="border rounded-full px-4 py-2">Foo</div>
  <div class="border rounded-full px-4 py-2">Bar</div>
  <div class="border rounded-full px-4 py-2">Baz</div>
</div>
```

From what I gathered it actually works like this?

```ts
customSelector(important(stacked(modifiers(class))))
```

I would have found it helpful, if the documentation contains a section about these two "special cases".

If you could provide a short snippet of how this should sound/look like I can also write up a PR for this.

**Comment by thecrypticace** [comment]
For arbitrary child selectors ("arbitrary variants") we document them here: https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants

They work and stack like other variants: right-to-left. The only difference is you're defining it inline instead of using the `addVariant` API — but the "string" you pass to it is the same. This means you can write things like this: `lg:[&:nth-child(3)]:hover:underline` and the `[&:nth-child(3)]` variant is treated the same as if you'd added a custom one called `nth-child-3`. I'm not certain if this necessitates an update to the docs — given that it's discussed just in a different section — but it's something we'll look over.

Important is actually handled _last_ in the pipeline but this isn't usually a useful distinction since it only affects properties themselves rather than the selector so it wouldn't really "matter" _unless_ you set an important **selector** which we cover here: https://tailwindcss.com/docs/configuration#selector-strategy

We also discuss in the preceding section where the `!` goes in the utility name: https://tailwindcss.com/docs/configuration#important-modifier

Since important doesn't affect the "stacking order" — which is specifically about variants / modifiers — that might not be something we add to that section since it's also discussed elsewhere. However, I'll bring this up with the team at the very least.

I can't really provide a snippet of how such changes should sound/look as it'll require a good bit of discussion internally to figure out what's best to do here. So for now I'm gonna close this. But thanks for bringing this up! I've added a note for us to look at this.

**Comment by spaceemotion** [comment]
Thanks for the quick, detailed response! I've read through the pages you've linked and that definitely clears things up.
If I knew where to look, this would have been easier 😅

Cheers!
