### ISSUE TITLE
Page layout has inconsistant overscroll behavior

### ISSUE THREAD

**Issue by r-nl** [tailwindlabs/tailwindcss.com#1681]
## Screenshot

https://github.com/tailwindlabs/tailwindcss.com/assets/113870088/d21fcc8c-f66f-463e-a11e-33a85cd23577

## Description

The header behaves strangely due to its sticky positioning compared to block positioning when overscrolling. It is extremely minor, but this may be fixed by applying the overscroll-y-none tailwind class to the body of the page, disabling overscroll and causing the header to behave more predictably.

**Comment by thecrypticace** [comment]
Heh this is a fun one. Thanks for the note about using `overscroll-y-none` as a way to kinda solve this.

Gonna leave myself some notes:

This is a quirk of Chrome/Blink when using `position: fixed`. Neither Safari nor Firefox showcase this behavior and instead move the fixed elements based on the overscroll amount. I'm not sure why we're using fixed instead of sticky for the sidebars but there is likely some reason for it. Would be good to look into as `position: sticky` does not have this problem.

Barring that we could definitely just stop all overscroll on the body element with `overscroll-y-none` as noted above.

**Comment by thecrypticace** [comment]
Hey, I did a little bit of investigation around this using `position: sticky` and switching to that will take a bit more work.

We generally like to stay on top of issues and keep them (and PRs) related to definite bugs, bug fixes, and occasional features. That paired with the thought that we probably don't want to disable over scroll (it can make things feel somewhat broken if you're not expecting it) means I'm going to close this one for now but I did make a note internally for us to revisit this probably next month when we can devote some more time to this specifically.
