### ISSUE TITLE
Play site missing paste option in Firefox

### ISSUE THREAD

**Issue by calalloo** [tailwindlabs/tailwindcss.com#1682]
https://play.tailwindcss.com/ missing paste option in Firefox https://prnt.sc/37W8ivBV6dJC

**Comment by adamwathan** [comment]
Weird one! It looks like Monaco doesn't register the paste command at all in Firefox because of the check it does that's outlined in this comment:

https://github.com/microsoft/monaco-editor/issues/1046#issuecomment-421282086

So there must be some browser API needed for this that Firefox doesn't support right now (or didn't the last time someone on the Monaco project worked on this feature).

There is this Firefox extension for adding paste to the menu for Monaco sites that maybe would be helpful:

https://addons.mozilla.org/en-CA/firefox/addon/paste-for-monaco/

I'm going to close this one as this is really an upstream issue that we probably can't fix without making a change to Monaco, but hope that additional context is helpful.

**Comment by calalloo** [comment]
> https://addons.mozilla.org/en-CA/firefox/addon/paste-for-monaco/

doesn't work outside of the specified sites.
