### ISSUE TITLE
Invalid configuration instructions for Angular (and possibly other frameworks) resulting in CSS not being loaded

### ISSUE THREAD

**Issue by Apokalypt** [tailwindlabs/tailwindcss.com#1712]
## What's the problem?
The instructions for installing TailwindCSS on Angular are correct, but may lead to errors in some cases (no indication of this)...
_This bug can occur with other frameworks, as the problematic part is largely shared with others._

The problematic step is "[Configure your template paths](https://tailwindcss.com/docs/guides/angular#:~:text=Configure%20your%20template%20paths)" and more specially how the path is written

## How to reproduce?
1. Follow the [setup guide for Angular](https://tailwindcss.com/docs/guides/angular)
2. Update your code to add some HTML with Tailwind CSS
3. Move to the subdirectory "app" and execute ``ng serve``
--> You will see that Angular is loaded but there is no CSS from tailwind

## Solution
Instead of writing ``"./src/**/*.{html,ts}"`` we should have in the documentation ``require('path').join(__dirname, '/src/**/*.{html,ts}')``. Using ``__dirname`` with ``path.join`` fix the problem where TailwindCSS isn't able to find files while starting the project through a subdirectory

If you don't want to update the documentation to include the use of ``path``, you should at least write a warning that project should always be start at the root of it!

**Comment by thecrypticace** [comment]
Hey so we don't cover this type of thing in the installation guides because if you follow them exactly you don't run into the problem. You're navigating to a subdirectory of the project and _then_ running `ng serve`. This doesn't strictly follow the installation guide which is meant to be a super simple walk through. We've written the guides to be as consistent as possible even across different types of projects.

The reason `ng serve` works in this scenario is their CLI walks up the directory tree and looks for an angular project and then starts it without changing the active working directory. However, not all CLI tools work this way but instead require you to start the server from the project root.

Having said that, we do support relative path resolution for content files which will also solve this problem for you. [We cover this in the docs](https://tailwindcss.com/docs/content-configuration#using-relative-paths) but we intentionally keep the installation guides simple.

Fwiw, we also cover using `require.resolve` and `path.join` on that same page as they're more relevant when using Tailwind CSS in monorepos.

We don't have any plans to change this currently so I'm gonna close this.
