### ISSUE TITLE
The header is not centered on the tailwindcss.com website.

### ISSUE THREAD

**Issue by NdekoCode** [tailwindlabs/tailwindcss.com#1721]
**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu

**Describe your issue**

The header is not centered on the tailwindcss.com website for large screens unlike other sections of the page.

Here's a video describing this

https://github.com/tailwindlabs/tailwindcss/assets/85836702/eb09569c-8d8c-467e-b7a7-220c70f799ee

**Comment by adamwathan** [comment]
Hey! Yep this is intentional, the header isn't meant to be constrained to a max-width like the other sections on the page.

GitHub homepage is designed the same way for example:

<img width="1728" alt="image" src="https://github.com/tailwindlabs/tailwindcss.com/assets/4323180/02399b3a-4c83-4cbf-b36e-9db5c7827541">
