### ISSUE TITLE
Feature Request: Shortlink on tailwindcss.com

### ISSUE THREAD

**Issue by minthemiddle** [tailwindlabs/tailwindcss.com#174]
- I want to propose making the current Tailwind available via `css.tailwindcss.com` in addition to just pointing to the CDN

Reasoning: 
- It is more accessible for beginners
- It is easy to tell a beginner: Just add `link` + tab and add `//css.tailwindcss.com` after the `<title>` line in jsbin.com
- I'm teaching a lot of total HTML/CSS newbies for my non-profit, all of them 13-17 years old
- We start by writing some easy classes in jsbin, already with a utility based approach and naming
- After 10 own rules I tell them: You could invent 1000s of own rules or use predefined
- But now I then point them to `tailwindcss.com` > Installation and ask them to copy the CDN link
- That creates confusion every time
- We host tailwind's CSS on our server (`css.code.design`)
- You could just CNAME forward to a CDN

**Comment by adamwathan** [comment]
This is a pretty cool idea! Moved the issue to the docs repo, will see about getting this done soon.

**Comment by adamwathan** [comment]
Looked into this and it's a little more work than just adding a CNAME since CNAMEs can only point to other domains, not complete paths. Closing in on 2 years since this was suggested and still haven't prioritized it so I think unfortunately I am just going to close this as a `wontfix`. May still do something like this in the future though, thanks for the suggestion.
