### ISSUE TITLE
Ring examples do not work in Firefox

### ISSUE THREAD

**Issue by rijenkii** [tailwindlabs/tailwindcss.com#1760]
Ring examples on pages [Ring Width](https://tailwindcss.com/docs/ring-width), [Ring Color](https://tailwindcss.com/docs/ring-color), [Ring Offset Width](https://tailwindcss.com/docs/ring-offset-width) and [RingOffsetColor](https://tailwindcss.com/docs/ring-offset-color) do not work.

Firefox 120.0.1, Fedora 39 x64.

Screenshots:
![image](https://github.com/tailwindlabs/tailwindcss.com/assets/5338332/9736530e-ee06-407e-80f0-a86b5a553fbd)
![image](https://github.com/tailwindlabs/tailwindcss.com/assets/5338332/037d2397-dbe4-468e-916b-b3c61815e331)

**Comment by thecrypticace** [comment]
Hey! This is because of a few things:
1. The Tailwind CSS website uses an internal / experimental feature to work around a perf issue in Safari because the page has nearly 8k elements on it.
2. This experiemental feature incorrectly groups rules contain `:has` with some other rules and invalidates the selector for the entire rule
3. Fedora 39 ships with Firefox 115 — which doesn't support `:has` — though FF 121 which does support it is available after a `yum upgrade`

These three things combined resulted in the rings disappearing after we added some examples using `has` to the docs.

I've updated things to fix this! Thanks for letting us know!
