### ISSUE TITLE
Redirect to v3 docs for /docs/configuring-variants

### ISSUE THREAD

**Issue by johnchourajr** [tailwindlabs/tailwindcss.com#1901]
Spent a good bit of time confused about making a plugin, and then realized that I had been looking at the v2 docs. 

## Expected behavior
Went to this link in Google search results: https://tailwindcss.com/docs/configuring-variants

## Actual results
I was taken to the v2 docs: https://v2.tailwindcss.com/docs/configuring-variants

----

When clicking v3.0, I was able to find the correct docs (this one, https://tailwindcss.com/docs/plugins#adding-variants), but was very confused for a good bit of time. 

Also, a my chat LLMs responses were all v2 related, which also confused me.

**Comment by adamwathan** [comment]
Hey! The page you linked has no real equivalent in v3 I'm afraid as there is no concept of configuring variants — that was a v2 and earlier thing where you needed to specify which variants existed for which utilities. So I feel like that redirect would be misleading, as the plugin stuff is a very different thing.

So going to keep this as-is for now but appreciate the feedback. If it turns out to be a common problem we can try and think of a better way to help people find what they were actually looking for.
