### ISSUE TITLE
Generating docs from a custom tailwind.config.js

### ISSUE THREAD

**Issue by krestaino** [tailwindlabs/tailwindcss.com#256]
It would be awesome if the docs could somehow utilize a project's custom `tailwind.config.js` and generate tailored docs with your custom values. The use case for this is working on a team, we could generate our own version of the Tailwinds docs instead of pointing new devs to the official docs, where some colors, utility names, and extended utilities would be missing.

**Comment by TobiObeck** [comment]
There is already a feature proposal (https://github.com/tailwindcss/docs/issues/81) to generate a cheat sheet based on the project which asks for basically the same, as far as I understand it.

**Comment by simonswiss** [comment]
Merging this with #81 👍

**Comment by mtsknn** [comment]
This would be great!

@simonswiss, are you referring to https://github.com/tailwindlabs/discuss/issues/81? That repo has been archived. Is there a newer relevant issue elsewhere? https://github.com/tailwindlabs/tailwindcss.com/issues/81 is only showing me "This issue has been moved to a repository you don't have access to or has been deleted since being transferred."

**Comment by simonswiss** [comment]
Oops - I think you're right! 😅

I'll turn this into a `discussion` since it's more a feature proposal than an actual issue. 👍
