### ISSUE TITLE
Any chance for a sitemap.xml?

### ISSUE THREAD

**Issue by godbout** [tailwindlabs/tailwindcss.com#355]
Hi!

I'm trying to maintain the [Dash](https://kapeli.com/dash) documentation docset for a couple of projects  and TailwindCSS is one of them, but I'm always having an issue updating because of the lack of sitemap.xml. Each time I need to review the pages and check manually that everything is referenced manually.

Do you think it would be possible for you add a sitemap? Thanks!

**Comment by reinink** [comment]
Hey! I agree that this is a good idea, but we don't have plans to prioritize this ourselves, so I'm going to close this, but happy to look at a PR if you want to put one together 👍

I know that @alany411 has done some work on this, but we were never able to get that merged in. The site has since been rebuilt, so that particular implementation will need to be updated.
