### ISSUE TITLE
Markdown example in the docs

### ISSUE THREAD

**Issue by jenstornell** [tailwindlabs/tailwindcss.com#409]
The markdown example you provided is a really good starting point.

**Two things about it:**

1. Good enough to be in the docs.
2. It's not compatible with the current Tailwind version. The color syntax has changed.

https://github.com/tailwindcss/discuss/issues/243

```css
.markdown {
  @apply text-lg text-grey-darkest leading-normal;
  & > * + *,  & li + li, & li > p + p {
    @apply mt-6;
  }
  & strong {
    @apply text-black font-bold;
  }
  & a {
    @apply text-black font-semibold;
  }
  & strong a {
    @apply font-bold;
  }
  & h2 {
    @apply leading-tight text-xl font-bold text-black mb-2 mt-10;
  }
  & h3 {
    @apply leading-tight text-lg font-bold text-black mt-8 -mb-2;
  }
  & code {
    @apply font-mono text-sm inline bg-grey-lighter px-1;
  }
  & pre code {
    @apply block bg-black p-4 rounded;
  }
  & blockquote {
    @apply border-l-4 border-grey-light pl-4 italic;
  }
  & ul, & ol {
    @apply pl-5;
    @screen sm {
      @apply pl-10;
    }
  }
}
```

**Comment by adamwathan** [comment]
Ah good catch, would merge a PR for this or will find time for it when I can.

**Comment by d4h0** [comment]
@adamwathan: Isn't this issue fixed with the [typography plugin](https://tailwindcss.com/docs/typography-plugin)?

On the other hand, the code sample probably still would be useful to some people who want full control over the styling...

Anyway, I will still post this comment, for people like me that find this issue via Google and don't know the typography plugin.

Btw., thanks a million for Tailwind! :)

**Comment by simonswiss** [comment]
Going to close this as the solution for this is indeed the [Typography plugin](https://tailwindcss.com/docs/typography-plugin).

The issue will remain searchable via Google even if closed 👍
