### ISSUE TITLE
Add Subresource Integrity to CDN instructions

### ISSUE THREAD

**Issue by pydanny** [tailwindlabs/tailwindcss.com#441]
Per [Mozilla on Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity):

> Subresource Integrity (SRI) is a security feature that enables browsers to verify that resources they fetch (for example, from a CDN) are delivered without unexpected manipulation. It works by allowing you to provide a cryptographic hash that a fetched resource must match.

CDNJS supports SRI as an dropdown option when selecting a resource

So instead of:

``` html
<link
rel="stylesheet" 
href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.4.6/tailwind.min.css"  />
```

You have:

``` html
<link
rel="stylesheet" 
href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.4.6/tailwind.min.css" 
integrity="sha256-CAI/7ThhltsmP2L2zKBYa7FknB3ZwFbD0nqL8FCdxdc=" 
crossorigin="anonymous" />
```

Again, the `integrity` value is provided by CDNJS, you don't have to do anything. Also, to the best of my knowledge, unpkg doesn't support SRI, so you might want to move examples from using them.

**Comment by adamwathan** [comment]
Hey! This is unfortunately non-trivial to implement since it needs to change every time we change the version, and since we generally discourage using CDN builds at all I don't think I can prioritize spending the time it would take to automate dynamically injecting the write snippet into the docs as new versions are released.

Happy to look at a PR if someone wants to do that, but going to close with no plans to prioritize this myself.
