### ISSUE TITLE
Font variant numeric utilities demo doesn't actually show the features

### ISSUE THREAD

**Issue by JakeNavith** [tailwindlabs/tailwindcss.com#522]
Page link: https://tailwindcss.com/docs/font-variant-numeric
OS: macOS 10.15.6
Browsers:
* Firefox (80.0.1 64-bit) [this is what the screenshot attached below was taken on]
* Chrome (85.0.4183.83 64-bit)
* Safari (13.1.2)

Problem: On the *font variant numeric* utilities documentation page, the features shown aren't actually working (i.e. they are still the normal font style / variant). See the attached screenshot for a more detailed look. 

Diagnosis:
In dev tools I saw that Source Sans Pro was loaded in successfully (i.e. had an underline in the `font-family` list) but that 
I think the main problem is that [the `/*!*/` trick described in the pull request for font variant numeric utilities](https://github.com/tailwindlabs/tailwindcss/pull/2305#issue-478802716) was purged away for the docs site, or it somehow has an incompatibility with `!important`. You can see that here (the crossed out declarations with ⚠️ ):
![image](https://user-images.githubusercontent.com/28162694/92310989-188dfe80-ef81-11ea-8a4f-046754604f83.png)

Possible solution (this is just conjecture): Fix the [purge](https://github.com/tailwindlabs/tailwindcss.com/blob/master/tailwind.config.js#L4) setting to not remove comments in the build used for the documentation site? But what's weird about that is that this isn't even a feature of PurgeCSS as far as I remember; it'd be more like CSSnano but you guys aren't even using that here 🤔.

![Font Variant Numeric - Tailwind CSS documentation site](https://user-images.githubusercontent.com/28162694/92310949-cd73eb80-ef80-11ea-9ff3-a87db6b31f10.png)

Hope this helps 👍

**Comment by adamwathan** [comment]
Thank you for reporting this! The underlying issue was that minifiers like cssnano and CleanCSS don't take into consideration the fact that `--my-custom-property: ;` is a valid value and remove things too aggressively.

We'd like to try and get this handled better upstream at some point but for now (after a bunch of experimentation) we found a truly awful hack that seems to work with all popular minifiers 😅 

https://github.com/tailwindlabs/tailwindcss/commit/f3660ceed391cfc9390ca4ea1a729a955e64b895

Released a new version that fixes this 👍

**Comment by JakeNavith** [comment]
It's live. Great work! 😄
