### ISSUE TITLE
Confusion around the theme override and extending

### ISSUE THREAD

**Issue by dominicumbeer** [tailwindlabs/tailwindcss.com#548]
## Use-Case / Problem

I recently tried to extend my theme by adding a negative value for `inset`. I didn't know how to do it back then. I opened the docs and found this [section](https://tailwindcss.com/docs/top-right-bottom-left#negative-values).

I copied the example code and adjusted it to my needs. A few previously working stylings broke. After some debugging, I realized that the theme change overrode all existing `inset` definitions. Instead, I should have applied the changes under `extend` context in the `tailwind.config.js` which extends the default theme.

## Question / Proposal

I'm wondering if the docs show the "override" intentionally by default? I can imagine that more users fall into that trap, and I'd like to improve the usability a bit.

- Can the docs use the `extend` pattern by default in customization settings like [here](https://tailwindcss.com/docs/top-right-bottom-left#customizing) and [here](https://tailwindcss.com/docs/z-index#customizing)?

- The [colors](https://tailwindcss.com/docs/customizing-colors) and [spacing](https://tailwindcss.com/docs/customizing-spacing) docs distinguish between override and extending well already.

I wanted to create a PR already but realized that I'd like to get some feedback first.

**Comment by simonswiss** [comment]
Hey @dominicumbeer!

You make a great point - I think the example here should show how to `extend` inset values instead of overriding the whole set.

> If you'd like to add any ...

That language ☝️ really makes it sound like this example will _add_ values, instead of creating a new set.

If you want to make a PR that wraps the couple of examples you mentioned, I think this would be a good improvement to the docs and I would be happy to merge this 👍

**Comment by simonswiss** [comment]
Merged - thanks for that! 👍
