### ISSUE TITLE
Ring Width + Box Shadow

### ISSUE THREAD

**Issue by tance77** [tailwindlabs/tailwindcss.com#608]
I was going through the classes and I got to ring width. https://tailwindcss.com/docs/ring-width I see an asterisk (*) it seems out of place and I wasn't sure if it was actually suppose to be there or not so I thought I would bring it up here.

![Screen Shot 2020-11-19 at 2 54 24 PM](https://user-images.githubusercontent.com/3421501/99734173-35fa4100-2a77-11eb-99c5-f7e7cdcf21df.png)
 
This also seems to be present in Box Shadow https://tailwindcss.com/docs/box-shadow

![Screen Shot 2020-11-19 at 2 56 37 PM](https://user-images.githubusercontent.com/3421501/99734345-883b6200-2a77-11eb-9eae-b2df16fb6de4.png)

**Comment by davidluhr** [comment]
@tance77 This is accurate and intentional, but something that hasn't been documented yet.

We found that without this zero-specificity selector, box shadows on wrapping elements were cascading to elements that were using the `ring-` classes. On focus, we were seeing the focus styles, but also the parent's box shadow. This "reset" prevents that from cascading.

I can see why it appears to there by mistake, but with some documentation, hopefully that will clarify things.

**Comment by tance77** [comment]
Awesome thanks for the clarification @davidluhr I'm not really sure how to use these in practice yet could you show an example for me.

I feel like they would overwrite each other because they are the same class name ```*```

**Comment by davidluhr** [comment]
@tance77 I believe this is included in Tailwind CSS 2.0 source code without any action needed on your part.
