### ISSUE TITLE
Switching between doc versions does not work

### ISSUE THREAD

**Issue by ahtik** [tailwindlabs/tailwindcss.com#661]
For example, looking at https://tailwindcss.com/docs/customizing-colors and choosing v1.9.0 brings to the front page, although https://v1.tailwindcss.com/docs/customizing-colors does exist.

Switching between the docs is quite helpful to understand the differences between the major version 2.

**Comment by adamwathan** [comment]
Hey! The current simple behavior is by design, but would accept a PR that made the switching attempt to preserve context. It's probably more work than it sounds like though because not every page exists in all versions. If there's no way to do it without maintaining a manual list then we unfortunately probably won't merge it, just don't want to take on that maintenance burden.

Going to close as this is is not something we intend to prioritize ourselves but again would be happy to review a PR.
