### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by juukee** [tailwindlabs/tailwindcss.com#671]
when i run `yarn build`，it doesn't know，change anthors PC，it look like npm command has problem。
![IMG_20201213_235308.jpg](https://user-images.githubusercontent.com/28680837/102016904-5c717a80-3d9e-11eb-88dc-7f8ff2f6b13f.jpg)![IMG_20201213_235502.jpg](https://user-images.githubusercontent.com/28680837/102016947-a5c1ca00-3d9e-11eb-974f-ffa9283dcce3.jpg)

**Comment by simonswiss** [comment]
Hey!

Not sure I understand what you mean by `it doesn't know, change authors PC` - do you have a bit more context on the what the error is and what situation it happens in?

**Comment by juukee** [comment]
When I run this `yarn build` or `yarn export`, the project command gets stuck and can't compile。

**Comment by RobinMalfait** [comment]
Hey! The build doesn't get stuck, it just takes a while...

We are doing a lot of stuff at build time, which improves the usability once everything is live (no need for a bunch of at-runtime things to happen). This has a downside that currently the build takes a while. We can improve this, but it is not the highest priority since it doesn't affect customers currently.

I just did a build on my machine, which took: 4m40s
