### ISSUE TITLE
Wrong link at the "Dark Mode" Documentation page

### ISSUE THREAD

**Issue by M00nD3v** [tailwindlabs/tailwindcss.com#680]
The Link ["Basic Usage"](https://tailwindcss.com/docs/dark-mode#basic-usage) from the right "ON THIS PAGE" scrollspy navigation is not working. Probably the anchor is missing/not set correctly.

**Comment by simonswiss** [comment]
Heh - thanks for pointing that out!

Turns out we forgot to import the `Heading` component on this page, so when using `<Heading>` in `MDX`, this is what the output was (instead of an `<h2>` tag 😅

![image](https://user-images.githubusercontent.com/485747/102304908-be0a3280-3fb2-11eb-8e46-995948cce381.png)

Will fix, thanks again 👍
