### ISSUE TITLE
Route not compiling

### ISSUE THREAD

**Issue by azzazkhan** [tailwindlabs/tailwindcss.com#693]
Route **/docs/installation** not compiling.

**Comment by adamwathan** [comment]
Hey! It compiles eventually just takes a very long time because it builds about 7 copies of Tailwind to generate statistics on different installation sizes. Once it builds the first time the expensive stuff is locally cached so it's quicker.

Going to close as not really an issue we are going to do anything about, it's just our own website and not even licensed for reuse so not really a concern to anyone else.

**Comment by azzazkhan** [comment]
I want to view tailwindcss docs offline.
