### ISSUE TITLE
Doc: defaults missing

### ISSUE THREAD

**Issue by nahuel** [tailwindlabs/tailwindcss.com#700]
It will be helpful to specify in the docs what is the default behaviour for each one of the utilities group (after you apply the `@tailwind base` preflight). For example, in https://tailwindcss.com/docs/flex-wrap it should be noticed that the `flex-nowrap` class behavior is the default one if you don't specify one.

**Comment by adamwathan** [comment]
Thanks for the suggestion, I think this is probably out of scope for our documentation if only because it's a massive project and requires studying and capturing the default values for every CSS property, and figuring out a way to incorporate that into the design of the site. We don't change too much in preflight relative to the size of the entire CSS API, so 99% of default behaviors you see are just regular browser defaults (including `flex-nowrap`).

Going to close with no plans to implement, but thanks again for the suggestion.
