### ISSUE TITLE
Docs typo for width classes

### ISSUE THREAD

**Issue by AlexMayol** [tailwindlabs/tailwindcss.com#718]
In [the documentation](https://tailwindcss.com/docs/width), it is written that `w-min` is for `width: min-content` and that `w-max` is for `width: max-content`. 

When producing the output in v `2.0.2`, the correct names are `w-min-content` and `w-max-content`.

![image](https://user-images.githubusercontent.com/11309999/105028219-0c4a9f80-5a51-11eb-9dd4-a9a8b8b7250b.png)

**Comment by adamwathan** [comment]
Hey! The correct names are definitely `w-max` and `w-min` — do you have the `@tailwindcss/ui` plugin installed by any chance? It added those utilities under those names before we added them to Tailwind CSS v2.0.

Here's the source code for generating these utilities:

https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L705-L706

...and here they are in our CDN output:

![image](https://user-images.githubusercontent.com/4323180/105503659-ddbd0680-5c94-11eb-9585-1cfa5f540b9d.png)

Closing since the docs are correct but thanks!
