### ISSUE TITLE
License for the documentation

### ISSUE THREAD

**Issue by manniL** [tailwindlabs/tailwindcss.com#75]
Hey :wave: 

Could you add a license file (or some other hint about the applicable license) for the documentation?

I guess it's MIT as Tailwind itself, right?

**Comment by adamwathan** [comment]
Would have to think about it a bit, as things stand I actually explicitly removed the license (inherited from Tailwind itself as both projects used to be one repo) because I don't really want to give people permission to wholesale copy our documentation design. Maybe will make it MIT one day but right now I think of it as proprietary, not unlike [laravel/laravel.com](https://github.com/laravel/laravel.com) for example.

**Comment by manniL** [comment]
@adamwathan Thanks for the fast feedback! :relaxed: 

Yeah, that makes totally sense. I release most of my written content also not under MIT but under CC-BY-SA(-NC).

I brought that issue up because tools like https://devdocs.io/ (where I'd love to see the tailwind docs in because of offline support) would need a clear license that allows them to add the docs to the page.

**Comment by nick-wireless** [comment]
I looked into cloning the docs for offline reading, only the need for Composer stumped me & I am not ready to dive into the PHP community just yet.  I am using devdocs.io for vue and other libraries while offline.  Adding another vote for one solution or the other.  (Thank you for all your work on this Adam.  Good luck with the pending 1.0 launch.)

**Comment by manniL** [comment]
@simonswiss There isn't a LICENSE.md file (or similar) in the repo so the issue still exists ☺️

**Comment by adamwathan** [comment]
Not planning to add one, just going to consider it proprietary but public for educational purposes 👍

**Comment by manniL** [comment]
Alright, thanks for the info 👌
