### ISSUE TITLE
static exportation resources doesn't load correctly

### ISSUE THREAD

**Issue by rezamirzapour** [tailwindlabs/tailwindcss.com#750]
I get export with "yarn export "command and it stores in "out" directory, but on every page, resources doesn't
 load and the links "href" doesn't take me to a correct page also
![Screenshot (56)](https://user-images.githubusercontent.com/45760028/107617439-2862ea80-6c65-11eb-91d3-30a2af0b604d.png)

**Comment by cristianpoleyJS** [comment]
Hello

It is because you are trying to render that index.html on the client and the URLs of the resources it is trying to access returns a 404, because it is missing the /out/ folder.

As discussed in this Issue: https://github.com/vercel/next.js/issues/8158#issuecomment-687707467, you can add this configuration in the `next.config.js`.

```
module.exports = {
    assetPrefix: "."
}
```

I tried it and it worked for me.

**Comment by adamwathan** [comment]
Hey! We don't host the site as a static export, it runs as on Vercel with a real Next.js server at run-time, so even if this is something we could make work unfortunately it's not at all a priority for us. The site is not licensed for reuse or anything (note the lack of LICENSE.md) and the code is only really public for people to contribute corrections and to use as an educational resource.
