### ISSUE TITLE
Use term "x-axis" instead of "cross axis"

### ISSUE THREAD

**Issue by tordans** [tailwindlabs/tailwindcss.com#767]
I am confused by the term "cross axis". Is it a synonym for "x-axis"? If so, I think "x-axis" would be the better term and I suggest to change the ~5 places is it used in the docs.

Eg. https://tailwindcss.com/docs/align-content#center

**Comment by adamwathan** [comment]
Hey! It's only the x-axis when `flex-direction` is `row`. When `flex-direction` is `column`, it becomes the y-axis. The terms "main axis" and "cross axis" are the official terminology used in all the flexbox spec/docs stuff which is why we used them in our docs 👍 

https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox#the_flex_model
