### ISSUE TITLE
why we have two same class inset-0 , -inset-0?

### ISSUE THREAD

**Issue by singleseeker** [tailwindlabs/tailwindcss.com#776]
Both inset-0 and -inset-0 have the same attributes.

```
{
  top: 0px;
  right: 0px;
  bottom: 0px;
  left: 0px;
}
```

Why we use these two same class?

**Comment by adamwathan** [comment]
This is honestly a bug that I didn't catch until it was too late and now that people are probably using both versions it's not going to be easy to remove :/ So the reason they exist is "oops I'm dumb" and unfortunately it's probably a bad idea to do anything about it, because it's intuitive for a lot of people to use the "negative-zero" version when trying to "undo" a negative value, like:

```html
<div class="-mt-6 md:-mt-0">
```
