### ISSUE TITLE
Lack of clarity for `safelist.txt` format

### ISSUE THREAD

**Issue by dane-skipper** [tailwindlabs/tailwindcss.com#805]
In the [Known Limitations](https://tailwindcss.com/docs/just-in-time-mode#known-limitations) section of the JIT documentation, the section on creating a `safelist.txt` feels a little ambiguous. I've played around to find a solution that works for me, but for the sake of future readers I think it would assist with clarity of usage to address the following:
- are the classes listed delimited by line breaks? Any whitespace? Something else?
- how does the compiler recognize the safelist? Does the compiler recognize the safelist conventionally by looking for a `safelist.txt` by name in project root? Can I name the safelist something else? How can I tell the compiler if the safelist is named something else?
- Do I have to use full class names in the safelist? Can I use patterns, as in PurgeCSS?
Example code and an example `safelist.txt` file would probably be the most helpful

Thank you, and all the best!

**Comment by dane-skipper** [comment]
One other minor thing that could be useful to clarify -- is there the possibility for comments in the `safelist.txt` format, and if so, how does one make one?

**Comment by TheLostXianXian** [comment]
in tailwindcss.config.js: 

purge: [
    './pages/**/*.{js,ts,jsx,tsx}', 
    './components/**/*.{js,ts,jsx,tsx}',
    './safelist.txt',
],

I found it worked for me and I use space to separate.

May it can help you.

**Comment by dane-skipper** [comment]
Yeah -- I ended up inferring from the recommended inclusion of `safelist.txt` in the purge list, and playing around with the contents of `safelist.txt` the following:
- the individual items of the safelist must be full class names (not globs, patterns, regexs, etc.)
- separating the items of the safelist with newlines works (I haven't tested other whitespace separators)

Anyways, for posterity's sake, this is what my safelist looks like:
```
class-1
variant-1:class-1
variant-2:class-1
class-1__type-1
class-1__type-2
variant-1:class-1__type-1
... etc ...
```

**Comment by adamwathan** [comment]
Yep you got it 👍🏻 We will eventually just support this properly so won't even need this file.

**Comment by browner12** [comment]
I have a large number of classes I need to safelist (~250), that are extracted from database fields that allow HTML. Currently I just have a `tailwind.blade.php` file that I put all these into, but I came across this issue because I wanted to check and make sure that was an okay way to do things. The only reason I don't want to put them directly in the `tailwind.config.js` file is simply because of their length.

@dane-skipper you referenced a `safelist.txt` file, but that doesn't appear anymore in the page you linked to, so I just wanted to put it in here in case anyone else is confused.

Is your current solution still to have a `safelist.txt` file with line-separated classes, and include that file in your `content` field?  If this still works, I think this is a great solution.

**Comment by dane-skipper** [comment]
@browner12 Yes -- that is our current solution (we also had the problem of having a large number of computed classes to safelist). I'll include a skeleton of our solution below in case seeing a concrete example will be helpful:
our `tailwind.config.js`:
```javascript
//...
module.exports = {
//...
   purge: {
      content: [
         './pages/**/*.*',
         './tailwind-class-safelist.txt'
      ]
   }
//...
}
```
the `tailwind-class-safelist.txt` looks identical to the one in my comment above (with line-separated classes).

**Comment by browner12** [comment]
Great, thanks for the response. This solution worked perfectly.
