### ISSUE TITLE
Selected menu item styling is near invisible to me

### ISSUE THREAD

**Issue by jamesbirtles** [tailwindlabs/tailwindcss.com#845]
Hi 👋 

I have a type of red-green colour blindness that I believe is stopping me from being able to see if a menu item is selected or not without really focusing on it. This makes it really difficult to know where I am in the sidebar after searching for something, to be able to see related utilities for example.

For me viewing the following, I cannot make out the edges of the highlight, and can just about see that its a light blue highlight when specifically focusing on it.
![Image showing the highlighting used on tailwindcss.com](https://user-images.githubusercontent.com/3743418/118291216-3c6df080-b4cf-11eb-8419-0be26b329d32.png)

It would be great if there was some other visual indication that a menu item is selected (e.g border, shadow, icon or similar), or using a different colour would help me specifically but maybe would just move the problem to some other colour blindness. Maybe just a gray highlight would be safe? (I'm not really familiar with other types of colour blindness so I'm unsure what would work best).

For now I've found a mode in windows that I can toggle on when viewing the docs that helps out.

Thanks

**Comment by reinink** [comment]
Hey @jamesbirtles, since you posted this message we have updated the website, and I'm hoping this problem no longer exists for you:

![image](https://user-images.githubusercontent.com/882133/148542030-dc9cd8ea-a8d8-4570-821b-3f252f6e6fa9.png)

We've also added a new dark mode version of the site which you might want to try:

![image](https://user-images.githubusercontent.com/882133/148542084-aed96292-55ea-43fa-b3c0-2f9e095b5c54.png)

Hope that helps! 🙏
