### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by justingolden21** [tailwindlabs/tailwindcss.com#874]
This would be great as a PWA. People could have the entire tailwind documentation available offline and easily install-able / accessible.

Given the number of pages, it's not practical to download each offline, but also since they're mostly text and images are infrequent and small, the file size would be fair as well.

**Comment by Mito9999** [comment]
Most of the mdx pages are less than 5KB, and there are around 100 so basically 0.5MB of pages, downloading them would be no challenge. However, they already load so fast as is, and documentation changes very frequently to where downloads would quickly become outdated.

**Comment by justingolden21** [comment]
> Most of the mdx pages are less than 5KB, and there are around 100 so basically 0.5MB of pages, downloading them would be no challenge. However, they already load so fast as is, and documentation changes very frequently to where downloads would quickly become outdated.

But that's my exact point. If you have no internet (for example, on a plane or in the car) then you have all of the pages offline. Otherwise, you could not have access to all of the pages offline, and since the file size is so small, it would be trivial to download.

**Comment by adamwathan** [comment]
Hey! I think this is a really cool idea but unfortunately no concrete plans to work on this right now, just too many other higher priority things to tackle and only limited resources. If there's a way to do this with like a 30-40 line code change I'm happy to take a look at a PR, but anything that involves significant reworking of the site probably will never realistically get reviewed or merged due to time constraints 😞

**Comment by justingolden21** [comment]
@adamwathan  No worries, it's all about opportunity cost in the end. I think making it a PWA would be a fairly reasonable change, maybe a bit more than 30-40 lines but not by much. You basically just need a 40ish line service worker script, and to have a manifest.json with the right icon sizes.
