### ISSUE TITLE
tab search not working.

### ISSUE THREAD

**Issue by Fanna1119** [tailwindlabs/tailwindcss.com#894]
On websites such as duckduckgo or google among others via chrome you can click tab in the url to search a query.
Would be awesome to have this little implementation on the tailwind site. 
https://www.chromium.org/tab-to-search

![gifcording-1626072718941](https://user-images.githubusercontent.com/4569097/125243634-a26bce00-e2ee-11eb-85b4-1769b26acc37.gif)

**Comment by adamwathan** [comment]
Hey! Thanks for the suggestion, will keep this in mind as maybe something to figure out how to support down the road. Unfortunately I don't think it's going to be a priority any time soon because I just have a lot of other much higher priority things to handle, but open to a PR if someone wants to explore it.
