### ISSUE TITLE
Style label instead of radio input in homepage code example

### ISSUE THREAD

**Issue by nordbit** [tailwindlabs/tailwindcss.com#907]
Section "Build whatever you want, seriously." there are example of clothes card,
Choosing size code is based on masked input tag and label, but wrong styled - input is styled, IMO label should be. 
Displayed card is based on ul -> li -> span, not connected to example code

**Comment by simonswiss** [comment]
Hey!

I think that's a fair comment re: that particular code example. In most places we try to keep the code examples somewhat lightweight to convey the styling approach rather than the absolute exact match to the component demo.

But yes, you're correct that the `label` should be styled instead of the input, probably something like this:

https://play.tailwindcss.com/6eRiy7vdep

Want to open a PR for it?

**Comment by reinink** [comment]
@nordbit We launched a new version of the website in December, which has this implemented correctly 👍
