### ISSUE TITLE
Why is the sample code on the official website different from the actual code?

### ISSUE THREAD

**Issue by haroldxing** [tailwindlabs/tailwindcss.com#983]
![image](https://user-images.githubusercontent.com/75294740/141233680-db8ef487-e309-4f87-b283-ce32cc3a8128.png)
![image](https://user-images.githubusercontent.com/75294740/141233860-f7a7d278-4080-4cdd-a5fb-e8d88aaa52b4.png)

**Comment by adamwathan** [comment]
Changed the markup in the demo after some people complained about it being not semantically correct but left the implementation because we had more important things to do.

Going to close because no concrete plans to prioritize changing this, but would be open to looking at a PR that made them the same without changing the design (we have a new design launching in a couple weeks though so would be best to wait until after that).
