### ISSUE TITLE
/docs/installation - app.js wrong path

### ISSUE THREAD

**Issue by rorar** [tailwindlabs/tailwindcss.com#984]
Hi,

I'm a newbie in VS Code and therefore in Tailwind.

**What happend**
I was tinkering around the issue that _no styles inside the public/styles.css is created_.

**What's the issue**
- The issue is that the documentation is outdated/not right when using the npm command
`npm install -D tailwindcss@latest postcss@latest autoprefixer@latest`
- With this script a folder _node_modules_ will be created
- tailwind will be installed inside the folder, therefore the tailwind.css
--> node_modules/tailwind/tailwind.css
- The docs pointing the tailwind.css inside the app.js to
`// app.js
import "tailwindcss/tailwind.css"`

**How to solve the issue**
- Solution 1: Giving the user a hint to check where the tailwind.css file is located
- Solution 2: Change the app.js path to 
`node_modules/tailwind/tailwind.css`

(As this is one of my first issue reports on GitHub, how am I doing? Can I do something better?)

**Comment by reinink** [comment]
Hey @rorar, so the reason `import "tailwindcss/tailwind.css"` works is because tools like webpack automatically resolve packages from your `node_modules` folder. Not sure why that's not working in your particular situation. Keep in mind that to do this you must be using a JavaScript framework like React or Vue that supports directly importing CSS files into your JS.

That said, I'd suggest just following our [updated installation guides](https://tailwindcss.com/docs/installation) (part of our new website launched in December), which recommend creating your own CSS file and then importing Tailwind CSS using our custom directives:

```css
/* app.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
```



Hope that helps 👍
