### ISSUE TITLE
Docs are confusing/lack on JIT: Why is purge still needed?

### ISSUE THREAD

**Issue by 205g0** [tailwindlabs/tailwindcss.com#988]
I thought, JIT is about generating __only used__ styles on the fly. Why do we still need to configure `purge` then?

**Comment by adamwathan** [comment]
JIT is in preview, so the documentation for it is all on this page:

https://tailwindcss.com/docs/just-in-time-mode

The documentation as a whole is written for the non-JIT engine, since that is the default and as of the most recent release JIT is still not considered stabled.

You still need to configure the `purge` key because that's how you tell Tailwind which files to scan for class names, even in JIT mode. If you don't configure that, Tailwind doesn't know where to look. In 3.0 (being released in 2 weeks, where JIT will be the default), the `purge` option has been renamed to `content` since `purge` isn't a very accurate name when using JIT. We kept it as `purge` while JIT is in preview to make it easy for people to switch between the two modes as they try it out.
