### ISSUE TITLE
Outline Example Uses border-blue, not ring-blue

### ISSUE THREAD

**Issue by Miserlou** [tailwindlabs/tailwindcss.com#990]
The first example appears to be wrong - at least to me - on this page: https://tailwindcss.com/docs/outline

The custom example uses the following code:

```html
<input type="text"
  placeholder="Custom focus style"
  class="focus:outline-none focus:ring focus:border-blue-300 ..." />
```

I would expect from this example that changing `focus:border-blue-300` to `focus:border-red-300` would make the border red, however it doesn't, and the ring remains blue.

I found conflicting documentation here: https://tailwindcss.com/docs/ring-color, which fixed the issue. So, I think the example should instead be:

```html
<input type="text"
  placeholder="Custom focus style"
  class="focus:outline-none focus:ring focus:ring-blue-300 ..." />
```

**Comment by adamwathan** [comment]
Hey! Docs are correct as far as I can tell, you can see on focus there is a light blue right, and a darker blue border:

![image](https://user-images.githubusercontent.com/4323180/143782088-4cb7b26d-f962-4bfd-9437-b0d688cc3ec9.png)

The `focus:ring` class is what creates the light blue ring, and `focus:border-blue-300` is what adds the darker blue border.

Adding `focus:border-rose-700` for example changes the border color as you can see here:

![image](https://user-images.githubusercontent.com/4323180/143782176-301b341c-6a83-443d-b072-e9b02af87a4e.png)

I think the reason you didn't see anything happen with `focus:border-red-300` (assuming you were changing it in dev tools) is that that class doesn't exist in our compiled CSS for the docs site because it's been purged out since it's unused 👍🏻
